# Generated by Django 4.0.3 on 2022-03-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_basevalueobject_device_booleanvalueobject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pulldevice',
            name='format',
            field=models.CharField(choices=[('csv', 'Csv'), ('parametres', 'Parametres')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pulldevice',
            name='source_address',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
