# Generated by Django 4.0.3 on 2022-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_device_device_name_pulldevice_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulldevice',
            name='source_type',
            field=models.CharField(choices=[('network', 'Network'), ('serial_bus', 'Serialbus')], default='network', max_length=20),
        ),
    ]
