# Generated by Django 4.0.3 on 2022-03-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_device_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='room',
        ),
    ]
