# Generated by Django 4.0.3 on 2022-03-18 16:49

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_device_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default=backend.models.default_set, on_delete=django.db.models.deletion.CASCADE, to='backend.room'),
        ),
    ]
