# Generated by Django 4.0.3 on 2022-03-19 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_device_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevalueslist',
            name='measurment_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
