# Generated by Django 4.0.3 on 2022-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_device_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevalueslist',
            name='measurment_time',
            field=models.DateTimeField(),
        ),
    ]
