# Generated by Django 4.0.3 on 2022-03-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_device_datetime_format'),
        ('backend', '0024_device_datetime_format'),
    ]

    operations = [
    ]
