# Generated by Django 4.0.3 on 2022-04-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_device_room_smartdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartDevice',
        ),
    ]
