# Generated by Django 4.0.3 on 2022-04-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_smartdevice_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartdevice',
            old_name='format',
            new_name='type',
        ),
    ]
