# Generated by Django 4.0.3 on 2022-03-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_room_manyvaluedevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneValueDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ValueObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.onevaluedevice')),
            ],
        ),
        migrations.DeleteModel(
            name='ManyValueDevice',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
