# Generated by Django 4.0.3 on 2022-03-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_onevaluedevice_valueobject_delete_manyvaluedevice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
