# Generated by Django 4.0.3 on 2022-03-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='valueobject',
            name='value_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='valueobject',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testdevice'),
        ),
        migrations.DeleteModel(
            name='OneValueDevice',
        ),
    ]
