# Generated by Django 4.0.3 on 2022-03-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_testdevice_alter_valueobject_value_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdevice',
            old_name='device_id',
            new_name='device_identifier',
        ),
    ]
