# Generated by Django 4.0.3 on 2022-03-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_device_id_testdevice_device_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valueobject',
            name='device',
        ),
        migrations.DeleteModel(
            name='TestDevice',
        ),
    ]
