# Generated by Django 4.0.3 on 2022-03-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_valueobject_device_delete_testdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestingValueObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testingdevice')),
            ],
        ),
        migrations.DeleteModel(
            name='ValueObject',
        ),
    ]
