# Generated by Django 4.0.3 on 2022-03-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_basevalueobject_device_devicevalueslist_room_and_more'),
        ('backend', '0009_basevalueobject_device_devicevalueslist_room_and_more'),
    ]

    operations = [
    ]
